#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service() {
    local enabled
    config_load ledstatus
    config_get enabled settings enabled '1'

    [ "$enabled" = "0" ] && return 0

    procd_open_instance
    procd_set_param command /usr/bin/led-status-check-daemon.sh
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    :
}

service_triggers() {
    procd_add_reload_trigger "ledstatus"
}
